### ISSUE TITLE
Confirm status of openEHR conformance tests

### ISSUE THREAD

**Issue by serefarikan** [DIPSAS/EhrStore.Postman#1]
First and foremost: thanks a lot. It is very kind of you to share your tests. 

Before I open other issues, could you please confirm that REST conformance tests in this repository are passing when used with DIPS implementation? I think I found some issues in the tests but I don't want to create 'github issues' before you confirm that these tests are passing. I.e. they're up to date and used against your implementation.

**Comment by bjornna** [comment]
Thanks!
They are up2date and used in our integration tests. Look forward to
feedback if you find abnormalities.

Den man. 18. mar. 2019, 14:08 skrev serefarikan <notifications@github.com>:

**Comment by serefarikan** [comment]
Thanks @bjornna .
