### ISSUE TITLE
Create EHR example: GENERIC_ID should have scheme

### ISSUE THREAD

**Issue by serefarikan** [DIPSAS/EhrStore.Postman#2]
The test payload used in the Create EHR (POST) request has external_ref/id with type GENERIC_ID .

As you can see [here](https://specifications.openehr.org/releases/BASE/latest/base_types.html#_identification_package): GENERIC_ID has a mandatory scheme attribute. The test payload is missing this attribute, therefore it was rejected by the Ocean implementation.

**Comment by fjukstad** [comment]
Thanks for the feedback @serefarikan ! 

We've updated the Create EHR payload in 9f804898026af10c937e0d3521e22f744e57e2fc with a scheme attribute.

**Comment by xinoframework** [comment]
thanks for the update.
